from PyInstaller.utils.hooks import collect_data_files

# The `coincurve._cffi` submodule is not automatically detected by PyInstaller.
# It is generated by `cffi` at runtime, so we need to collect its data files
# in order for it to be importable.
# This is the standard, community-approved hook for the `coincurve` library.
datas = collect_data_files('coincurve._cffi') 